# Generated by Django 3.2 on 2021-05-09 18:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_auto_20200502_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
